pipeline {
    agent any
    tools {
        "org.jenkinsci.plugins.terraform.TerraformInstallation" "terraform-0.11.8"
    }
    parameters {
        string(name: 'LAMBDA_URL', defaultValue: '', description: 'URL to the Lamdba function')
        string(name: 'WORKSPACE', defaultValue: 'development', description:'worspace to use in Terraform')
        string(name: 'DYNAMODBTABLE', defaultValue: 'ned-ddt-tfstatelock', description:'DynamoDB table to store state lock info')
        string(name: 'NETREMOTESTATEBUCKET', defaultValue: 'ned-ddt-networking', description: 'S3 Bucket to store remote state')
    }
    environment {
        TF_HOME = tool('terraform-0.11.8')
        TF_IN_AUTOMATION = "true"
        PATH = "$TF_HOME:$PATH"
        NETWORKING_ACCESS_KEY = credentials('networking_access_key')
        NETWORKING_SECRET_KEY = credentials('networking_secret_key')
    }
    stages {
        stage('NetworkInit'){
            steps {
                dir('ThirdDemo/networking/'){
                    sh 'terraform --version'
                    sh "terraform init -input=false -plugin-dir=/var/jenkins_home/terraform_plugins \
                     --backend-config='dynamodb_table=${params.DYNAMODBTABLE}' --backend-config='bucket=${params.NETREMOTESTATEBUCKET}' \
                     --backend-config='access_key=$NETWORKING_ACCESS_KEY' --backend-config='secret_key=$NETWORKING_SECRET_KEY'"
                    sh "echo \$PWD"
                    sh "whoami"
                }
            }
        }
        stage('NetworkPlan'){
            steps {
                dir('ThirdDemo/networking/'){
                    script {
                        try {
                           sh "terraform workspace new ${params.WORKSPACE}"
                        } catch (err) {
                            sh "terraform workspace select ${params.WORKSPACE}"
                        }
                        sh "terraform plan -var 'aws_access_key=$NETWORKING_ACCESS_KEY' -var 'aws_secret_key=$NETWORKING_SECRET_KEY' \
                        -var 'url=${params.LAMBDA_URL}' -out terraform-networking.tfplan;echo \$? > status"
                        stash name: "terraform-networking-plan", includes: "terraform-networking.tfplan"
                    }
                }
            }
        }
        stage('NetworkApply'){
            steps {
                script{
                    def apply = false
                    try {
                        input message: 'confirm apply', ok: 'Apply Config'
                        apply = true
                    } catch (err) {
                        apply = false
                        dir('ThirdDemo/networking'){
                            sh "terraform destroy -var 'aws_access_key=$NETWORKING_ACCESS_KEY' \
                             -var 'aws_secret_key=$NETWORKING_SECRET_KEY' -var 'url=${params.LAMBDA_URL}' -force"
                        }
                        currentBuild.result = 'UNSTABLE'
                    }
                    if(apply){
                        dir('ThirdDemo/networking'){
                            unstash "terraform-networking-plan"
                            sh 'terraform apply terraform-networking.tfplan'
                        }
                    }
                }
            }
        }
    }
}